core:
  - changed-files:
      - any-glob-to-any-file: ['internal/core/**']

adapters:
  - changed-files:
      - any-glob-to-any-file: ['internal/adapters/**']

infra:
  - changed-files:
      - any-glob-to-any-file: ['internal/infra/**']

delivery:
  - changed-files:
      - any-glob-to-any-file: ['internal/delivery/**']

tui:
  - changed-files:
      - any-glob-to-any-file: ['tui/**']

docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
